services:
  db:
    image: postgres:15
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    networks:
      - chanx-example

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - chanx-example

volumes:
  dbdata:

networks:
  chanx-example:
    driver: bridge
